// Generated by CoffeeScript 1.8.0
var arrowHeight;

container.css({
  'height': contentHeight
});

$('.site').css({
  'height': contentHeight
});

arrowHeight = $('.right-menu-trigger').position().top - 150;

$('nav.arrows').css({
  'padding-top': arrowHeight + 'px'
});

$('.left-menu-trigger').on('click', function() {
  return menuContainer.toggleClass('menu-open-left');
});

$('.right-menu-trigger').on('click', function() {
  return menuContainer.toggleClass('menu-open-right');
});

$('span.close').on('click', function() {
  if ($(this).parent().parent().hasClass('left')) {
    return menuContainer.toggleClass('menu-open-left');
  } else {
    return menuContainer.toggleClass('menu-open-right');
  }
});
